RABBITMQ_SERVICE_HOST: localhost
RABBITMQ_SERVICE_PORT: 5672
RABBITMQ_SERVICE_USERNAME: guest
RABBITMQ_SERVICE_PASSWORD: guest
#spring.sleuth.sampler.probability: 1.0  
#spring.zipkin.baseUrl: http://localhost:9411/
   
tracer.property: "I AM THE Default"
success.message: Data saved succesfully.
spring.jpa.database: "mysql"
spring.datasource.platform: "mysql"
spring.jpa.show-sql: "true"

spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"


spring.jpa.hibernate.ddl-auto: update
spring.jpa.generate-ddl: true

#spring.datasource.url: "jdbc:mysql://100.120.56.176:3307/organizationmicroservice"
spring.datasource.url: "jdbc:mysql://192.168.1.3:3307/organizationmicroservice"
spring.datasource.username:  db_user
#spring.datasource.password: "{cipher}b4d96af236cc7ae0f4e39ba2f23facecc0a191392a5476b4fd14a3e0ed60e0ea"
spring.datasource.password: "db_user"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
spring.database.driverClassName: com.mysql.jdbc.Driver


spring: 
    cloud:    
      stream:
        bindings:
          output:
            destination: inboundOrgChanges
            binder: local_rabbit
            content-type: application/json
            group: organizationService
        binders:
          local_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                    host: ${RABBITMQ_SERVICE_HOST}
                    port:  ${RABBITMQ_SERVICE_PORT}
                    username: ${RABBITMQ_SERVICE_USERNAME}
                    password: ${RABBITMQ_SERVICE_PASSWORD}
                    virtual-host: /
    zipkin:
        enabled: true
        service:
            name: organizationService
        sender:
            type: web
        base-url: http://localhost:9411
    sleuth:
        enabled: true
        sampler:
            probability: 1.0
            
management.endpoint.chaosmonkey.enabled: true

# include specific endpoints
management.endpoints.web.exposure.include: health,info,chaosmonkey,hystrix.stream                  